name: ne_kidaem
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  dio: 4.0.4
  flutter_bloc: 8.0.1
  hive: 2.0.5
  connectivity: 3.0.6
  path_provider: 2.0.8
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/languages/en.json
    - assets/languages/ru.json
